### ISSUE TITLE
Codes for Megaportrait

### ISSUE THREAD

**Issue by JZArray** [mbzuai-metaverse/VOODOO3D-official#8]
Hello guys, nice work! Could you also provide your codes of Megaportrait?

Thanks in advance!

**Comment by Mrkomiljon** [comment]
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\TEST\VOODOO3D-official\test_voodoo3d.py", line 119, in <module>
    main()
  File "C:\Users\USER\miniconda3\envs\voodoo3d\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\USER\miniconda3\envs\voodoo3d\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\USER\miniconda3\envs\voodoo3d\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\USER\miniconda3\envs\voodoo3d\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\USER\miniconda3\envs\voodoo3d\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\USER\Desktop\TEST\VOODOO3D-official\test_voodoo3d.py", line 72, in main
    driver_data = processor.from_path(driver_path, device, keep_bg=False)
  File "C:\Users\USER\Desktop\TEST\VOODOO3D-official\data_preprocessing\data_preprocess.py", line 66, in from_path
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
who is facing like this issue?

**Comment by P0lyFish** [comment]
@JZArray Hey, sorry that I forgot to reply your issue (we are pretty busy right now because of the conference).

For MegaPortraits code, I have to double check with my lab and other collaborators if I can release it or not. In case we can release (which is likely), it may also take a while to polish the code for MegaPortraits to and I may have to create a separate repo for it.

**Comment by JZArray** [comment]
> @JZArray Hey, sorry that I forgot to reply your issue (we are pretty busy right now because of the conference).
> 
> For MegaPortraits code, I have to double check with my lab and other collaborators if I can release it or not. In case we can release (which is likely), it may also take a while to polish the code for MegaPortraits to and I may have to create a separate repo for it.

@P0lyFish Thanks for your relpy! I understand what you said, and is it possible first to provide parts of codes(like: how you implement the warp opearation for Vs using predicted warp fileds Ws and Wd).

**Comment by johndpope** [comment]
there's this implementation of code - maybe you can 'upgrade' it to work properly - https://github.com/johndpope/MegaPortrait-hack

**Comment by JZArray** [comment]
@P0lyFish hallo, cvper conference is over, do you have time now to updata codes?

**Comment by JZArray** [comment]
@P0lyFish hallo, any plan to update codes?
